#!/usr/bin/env bash
#Display the time for 12 hrs and 59 mins.

hour=0

while ((hour < 13))

do

    echo "Hour: $((hour++))"

    minute=1

    while ((minute < 60))

    do

        echo "$((minute++))"

    done

done
